const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>n==null?'미기재':Number(n).toLocaleString('ko-KR')+'원',count=n=>Number(n).toLocaleString('ko-KR');
let data=LabData.empty(),user={role:'student'},version=0,students=[],tab='home',term='2026-2 인건비(안)',confKind='all',busy=false,exportRows=[];
const offline=!!globalThis.LAB_PREVIEW,admin=()=>user.role==='admin';
const menu=[['home','연구실 현황'],['papers','논문'],['conferences','학회 발표'],['funds','연구비'],['payroll','인건비'],['settings','자료·계정 관리']];
const filter=rows=>rows.filter(r=>($('year').value==='all'||String(r.year)===$('year').value)&&JSON.stringify(r).toLowerCase().includes($('query').value.trim().toLowerCase()));
const badge=s=>`<span class="badge">${esc(s)}</span>`;
function table(headers,rows,classes=[]){if(!rows.length)return '<div class="empty">선택한 조건에 해당하는 자료가 없습니다.</div>';return `<div class="table-wrap"><table class="data-table"><thead><tr>${headers.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map((v,i)=>`<td class="${classes[i]||''}">${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
const card=(label,value,note)=>`<div class="card"><span class="label">${esc(label)}</span><span class="value">${esc(value)}</span><small>${esc(note)}</small></div>`;
function bar(label,value,max,light=false){return `<div class="bar-row"><span>${esc(label)}</span><div class="track"><div class="fill ${light?'light':''}" style="width:${max?value/max*100:0}%"></div></div><strong>${count(value)}</strong></div>`;}
function nav(){ $('tabs').innerHTML=menu.filter(([k])=>admin()||['home','papers','conferences'].includes(k)).map(([k,v])=>`<button class="tab ${k===tab?'active':''}" data-tab="${k}" aria-current="${k===tab?'page':'false'}">${v}</button>`).join('');$('filters').classList.toggle('hidden',!['home','papers','conferences'].includes(tab));$('tabs').querySelectorAll('button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render();});}
function years(){const old=$('year').value;const list=[...new Set([...data.papers,...data.conferences].map(r=>r.year).filter(Boolean))].sort((a,b)=>b-a);$('year').innerHTML='<option value="all">전체 연도</option>'+list.map(y=>`<option>${y}</option>`).join('');$('year').value=list.includes(Number(old))?old:'all';}
function render(){nav();exportRows=[];const panel=$('panel'),p=filter(data.papers),c=filter(data.conferences);const title=menu.find(([k])=>k===tab)[1];let html=`<h1>${title}</h1>`;
 if(tab==='home'){
  const awards=c.filter(r=>/우수|수상|최우수/.test(r.note));html+=`<div class="cards">${card('등록 논문',p.length+'건','게재 여부 미확인 · 예정 목록 포함')}${card('학회 발표 기록',c.length+'건','원본에 등록된 발표 내역')}${card('발표자',new Set(c.map(r=>r.presenter)).size+'명','선택 기간의 고유 발표자')}${card('수상 표시 기록',awards.length+'건','비고에 수상·우수 표시')}</div>`;
  const ys=[...new Set([...p,...c].map(r=>r.year))].sort((a,b)=>a-b),counts=ys.map(y=>({year:y,p:p.filter(r=>r.year===y).length,c:c.filter(r=>r.year===y).length})),max=Math.max(1,...counts.flatMap(r=>[r.p,r.c]));
  html+=`<div class="grid"><div class="section-card"><h2>연도별 연구 기록</h2>${counts.length?counts.map(r=>bar(r.year+' 논문',r.p,max)+bar('발표',r.c,max,true)).join(''):'<p class="muted">원본 자료를 등록해주세요.</p>'}<div class="legend"><span><i class="swatch"></i>등록 논문</span><span><i class="swatch light"></i>발표 기록</span></div></div><div class="stack"><div class="section-card"><h2>발표 유형</h2>${['구두','포스터','미기재'].map(k=>bar(k,c.filter(r=>r.kind===k).length,Math.max(1,c.length))).join('')}<p class="muted">유형이 비어 있는 발표는 미기재로 분류합니다.</p></div><div class="section-card"><h2>최근 발표 기록</h2>${[...c].sort((a,b)=>b.year-a.year||b.date.localeCompare(a.date)).slice(0,4).map(r=>`<div class="event"><div class="event-date">${esc(r.year)}<br>${esc(r.date.slice(5)||'날짜 미상')}</div><div><strong>${esc(r.conference)}</strong><p>${esc(r.presenter)} · ${esc(r.kind)}</p></div></div>`).join('')||'<p class="muted">등록된 발표가 없습니다.</p>'}</div></div></div><div class="note">현재 화면은 업로드된 기록을 기준으로 합니다. 논문 게재 상태·학회 마감일은 원본에 별도 항목이 없어 확정 실적이나 예정 일정으로 표시하지 않습니다.</div>`;
 }else if(tab==='papers'){
  html+='<div class="note">원본 Paper 시트를 기준으로 통합했습니다. 홈페이지 게시용·생애업적 시트는 중복 합산하지 않습니다. IF와 업적평가 점수는 서로 다른 값입니다.</div>';
  const headers=['연도','논문 제목','학술지','저자 구분','연계 과제','등록 구분'];const rows=p.slice().sort((a,b)=>b.year-a.year).map(r=>[r.year,r.title,r.journal||'미기재',r.role,r.fund||'미기재',r.status]);exportRows=[headers,...rows];html+=toolbar(rows.length)+table(headers,rows.map(r=>r.map(esc)),['nowrap','title','title','nowrap','','nowrap']);
 }else if(tab==='conferences'){
  const records=c.filter(r=>confKind==='all'||r.kind===confKind);const headers=['연도','발표일 / 기간','발표자','학회·장소','발표 제목','유형','비고'];const rows=records.slice().sort((a,b)=>b.year-a.year||b.date.localeCompare(a.date)).map(r=>[r.year,r.date||r.period||'미기재',r.presenter,r.conference+' · '+r.region+' / '+r.venue,r.title||'미기재',r.kind,r.note]);exportRows=[headers,...rows];html+=`<div class="toolbar"><label>발표 유형 <select id="kind"><option value="all">전체</option>${['구두','포스터','미기재'].map(k=>`<option ${confKind===k?'selected':''}>${k}</option>`).join('')}</select></label></div>`+toolbar(rows.length)+table(headers,rows.map(r=>r.map(esc)),['nowrap','nowrap','nowrap','title','title','nowrap','']);
 }else if(tab==='funds'){
  html+='<div class="note">기본연구소 연구비만 표시합니다. 연구실 전체 연구비가 아니며, 각 표의 원본 잔액과 기간을 유지합니다.</div>';
  for(const f of data.funds){const spend=f.months.reduce((s,m)=>s+m.spend,0);html+=`<div class="section-card" style="margin-bottom:20px"><h2>${esc(f.title)} ${f.closed?badge('사용완료 메모'):badge('기록 잔액')}</h2><p class="muted">원본 시트: ${esc(f.sheet)}</p><div class="cards" style="grid-template-columns:repeat(3,1fr)">${card('표에 기록된 총액',money(f.total),'원본 입력값')}${card('표 내 지출 합계',money(spend),'월별 입력 금액 합산')}${card('마지막 기록 잔액',money(f.balance),f.closed?'사용완료 · 가용액 아님':'예정 지출 반영 여부 미확인')}</div>${table(['월(원본 표기)','기록 지출','기록 잔액'],f.months.map(m=>[esc(m.month),money(m.spend),money(m.balance)]),['','money','money'])}<p class="muted">${esc(f.note)}</p></div>`;}
  if(!data.funds.length)html+='<div class="empty">연구비 파일을 등록해주세요.</div>';
 }else if(tab==='payroll'){
  const terms=[...new Set(data.payroll.map(r=>r.term))];if(!terms.includes(term))term=terms[0]||'';const rs=data.payroll.filter(r=>r.term===term);html+=`<div class="toolbar"><label>지급 계획 <select id="term">${terms.map(t=>`<option ${t===term?'selected':''}>${esc(t)}</option>`).join('')}</select></label>${badge('교수님 전용')}</div><div class="note warning">지급계획표를 표시하며 실제 지급 완료를 의미하지 않습니다. (안) 표기를 유지하고, 월 합계와 학기 금액이 다르더라도 원본 값을 임의로 바꾸지 않았습니다.</div><div class="cards" style="grid-template-columns:repeat(3,1fr)">${card('계획 행 수',rs.length+'명분','xxx 등 미정 인원 포함')}${card('월 합계',money(rs.reduce((s,r)=>s+(r.monthly||0),0)),'원본 H열 합계')}${card('학기 합계',money(rs.reduce((s,r)=>s+(r.semester||0),0)),'원본 I열 합계')}</div>`;
  const headers=['이름','과정 / 장학','기준 월급','핵심연구A','기관계정','SRC','월 합계','학기 금액','확인'];const rows=rs.map(r=>[r.name,r.degree+' / '+r.scholarship,money(r.base),money(r.core),money(r.institution),money(r.src),money(r.monthly),money(r.semester),r.monthly*6!==r.semester?'월×6 불일치':r.name==='xxx'?'미정 인원':r.note]);exportRows=[headers,...rows];html+=toolbar(rows.length)+table(headers,rows.map(r=>r.map(esc)),['nowrap','nowrap','money','money','money','money','money','money','title']);
  html+='<details><summary>2026 과정별 지급 기준</summary>'+table(['과정','기본 월 인건비','BK 지원금','BK 포함 월 수령액','등록금 고려 월액'],data.standards.map(r=>[esc(r.degree),money(r.base),money(r.bk),money(r.total),money(r.afterTuition)]),['','money','money','money','money'])+'</details>';
 }else{
  html+=`<div class="grid"><div class="section-card"><h2>엑셀 자료 갱신</h2><p class="muted">기존 양식의 파일을 선택하면 해당 자료만 교체합니다. 논문·학회·연구비·인건비 파일을 한 번에 선택할 수 있습니다.</p><label class="primary green" style="display:inline-block;cursor:pointer">엑셀 선택<input class="hidden" id="upload" type="file" accept=".xlsx" multiple></label><p id="uploadStatus" class="status" role="status"></p>${data.sources.map(s=>`<div class="source"><strong>${esc(s.name)}</strong><div class="muted">불러온 날짜 ${esc(s.importedAt.slice(0,10))}</div></div>`).join('')}<p class="muted">현재는 파일 업로드 방식입니다. 구글 시트 자동 동기화는 아직 연결하지 않았습니다.</p></div><div class="stack"><div class="section-card"><h2>학생 접근 계정</h2><p class="muted">학생은 논문·학회만 조회합니다. 연구비·인건비는 서버에서 제외합니다.</p><label for="students">학생 이메일 · 한 줄에 한 명</label><textarea id="students" rows="5" style="width:100%;margin:10px 0" placeholder="student@ajou.ac.kr">${esc(students.join('\n'))}</textarea><button id="saveStudents" class="primary" ${offline?'disabled':''}>접근 목록 저장</button><p class="muted">${offline?'검토용 파일에서는 계정 설정을 저장할 수 없습니다.':'Sites에서 사이트 공유 권한도 별도로 부여해야 합니다.'}</p><p class="status" id="accountStatus" role="status"></p></div><div class="section-card"><h2>원본 확인 사항</h2>${data.issues.length?'<ul>'+data.issues.map(i=>`<li style="margin-bottom:10px;font-size:14px">${esc(i.message)}</li>`).join('')+'</ul>':'<p class="muted">등록된 확인 사항이 없습니다.</p>'}</div></div></div>`;
 }
 panel.innerHTML=html;
 if($('kind'))$('kind').onchange=e=>{confKind=e.target.value;render();};if($('term'))$('term').onchange=e=>{term=e.target.value;render();};if($('csv'))$('csv').onclick=download;
 if($('upload'))$('upload').onchange=upload;if($('saveStudents'))$('saveStudents').onclick=saveStudents;
 const dates=data.sources.map(s=>s.importedAt).sort();$('sourceDate').textContent=dates.length?'자료 불러온 날짜 '+dates.at(-1).slice(0,10):'원본 자료 미등록';
}
function toolbar(n){return `<div class="toolbar"><span class="muted">${count(n)}개 기록</span><button class="secondary" id="csv">현재 표 CSV 저장</button></div>`;}
function download(){const cell=v=>{let s=String(v??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};const b=new Blob(['\ufeff'+exportRows.map(r=>r.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(b),a=document.createElement('a');a.href=url;a.download='연구실_'+tab+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function put(path,input){const res=await fetch(path,{method:'PUT',headers:{'Content-Type':'application/json','X-Lab-Request':'1'},body:JSON.stringify({version,...input})});const result=await res.json();if(!res.ok)throw Error(result.error);version=result.version;}
async function upload(e){if(busy)return;const input=e.target;busy=true;input.disabled=true;const files=[...input.files];$('uploadStatus').textContent='엑셀을 읽고 있습니다…';try{let updated=structuredClone(data);for(const f of files){const sheets=await LabData.readXlsx(f);updated=LabData.merge(updated,LabData.normalize(sheets,f.name));}if(!offline)await put('/api/data',{data:updated});data=updated;years();render();$('uploadStatus').textContent=offline?'이 검토 화면에 반영했습니다. 파일을 다시 열면 원래 사본으로 돌아갑니다.':'자료를 저장했습니다.';}catch(err){$('uploadStatus').textContent=err.message;}finally{busy=false;input.disabled=false;input.value='';}}
async function saveStudents(){const b=$('saveStudents');b.disabled=true;try{const next=$('students').value.split(/\s+/).filter(Boolean);await put('/api/students',{students:next});students=next;$('accountStatus').textContent='접근 목록을 저장했습니다.';}catch(e){$('accountStatus').textContent=e.message;}finally{b.disabled=false;}}
$('year').onchange=render;$('query').oninput=render;$('reset').onclick=()=>{$('year').value='all';$('query').value='';confKind='all';render();};
function theme(mode){document.documentElement.dataset.theme=mode;$('theme').textContent=mode==='dark'?'라이트 모드':'다크 모드';try{localStorage.setItem('ajou-lab-theme',mode);}catch{}}
try{theme(localStorage.getItem('ajou-lab-theme')||'light');}catch{theme('light');}$('theme').onclick=()=>theme(document.documentElement.dataset.theme==='dark'?'light':'dark');
(async()=>{try{if(offline){data=LAB_PREVIEW;user={email:'',role:'admin'};$('previewNotice').classList.remove('hidden');}else{const res=await fetch('/api/data',{cache:'no-store'}),result=await res.json();if(!res.ok)throw Error(result.error);({data,user,version,students}=result);}years();const current=String(new Date().getFullYear());if([...$('year').options].some(o=>o.value===current))$('year').value=current;$('userLabel').innerHTML=badge(admin()?'교수님':'연구실 구성원');render();}catch(e){$('userLabel').textContent='연결 필요';$('panel').innerHTML=`<div class="note warning">${esc(e.message)}</div>`;}})();
