import test from 'node:test';import assert from 'node:assert/strict';import {createWorker,fresh,visible} from '../server/worker.mjs';
const OWNER='owner@example.test';
function fixture(){const state=fresh();state.students=['student@example.test'];state.data.papers=[{title:'A',year:2026,points:100,engineeringPoints:200}];state.data.payroll=[{name:'PRIVATE_PERSON',monthly:100}];state.data.funds=[{balance:500,months:[]}];let row={version:0,payload:JSON.stringify(state)};const DB={prepare(sql){return {bind(...a){this.a=a;return this;},async first(){return {...row};},async run(){if(sql.startsWith('UPDATE')){if(this.a[1]!==row.version)return {meta:{changes:0}};row={version:row.version+1,payload:this.a[0]};return {meta:{changes:1}};}return {meta:{changes:0}};}};}};return {env:{DB,ADMIN_EMAIL:OWNER},worker:createWorker('<p>Dashboard</p>')};}
const req=(email,path='/api/data',method='GET',body)=>new Request('https://lab.example'+path,{method,headers:{...(email?{'oai-authenticated-user-id':'verified-id','oai-authenticated-user-email':email}:{}),...(method==='PUT'?{'Origin':'https://lab.example','Content-Type':'application/json','X-Lab-Request':'1'}:{})},...(body?{body:JSON.stringify(body)}:{})});
test('anonymous and unapproved users cannot read HTML or API',async()=>{const {worker,env}=fixture();assert.equal((await worker.fetch(req(null),env)).status,401);assert.equal((await worker.fetch(req('unknown@example.test','/'),env)).status,403);});
test('student API excludes financial data and faculty points',async()=>{const {worker,env}=fixture();const r=await worker.fetch(req('student@example.test'),env);assert.equal(r.status,200);const d=await r.json();assert.deepEqual(d.data.payroll,[]);assert.deepEqual(d.data.funds,[]);assert.ok(!JSON.stringify(d).includes('PRIVATE_PERSON'));assert.equal(d.data.papers[0].points,undefined);assert.deepEqual(d.students,[]);});
test('student cannot upload data or grant accounts',async()=>{const {worker,env}=fixture();for(const path of ['/api/data','/api/students'])assert.equal((await worker.fetch(req('student@example.test',path,'PUT',{version:0,data:fresh().data,students:[]}),env)).status,403);});
test('owner updates persist and stale saves are rejected',async()=>{const {worker,env}=fixture();const input={version:0,students:['new@example.test']};assert.equal((await worker.fetch(req(OWNER,'/api/students','PUT',input),env)).status,200);assert.equal((await worker.fetch(req(OWNER,'/api/students','PUT',input),env)).status,409);assert.equal((await worker.fetch(req('new@example.test'),env)).status,200);assert.equal((await worker.fetch(req('student@example.test'),env)).status,403);});
test('cross origin mutation blocked',async()=>{const {worker,env}=fixture(),r=req(OWNER,'/api/data','PUT',{version:0,data:fresh().data});r.headers.set('Origin','https://other.example');assert.equal((await worker.fetch(r,env)).status,403);});
