import test from 'node:test';import assert from 'node:assert/strict';import {createWorker,fresh,visible} from '../server/worker.mjs';
const OWNER='owner@example.test';
function fixture(){const state=fresh();state.students=['student@example.test'];state.data.papers=[{title:'A',year:2026,points:100,engineeringPoints:200}];state.data.payroll=[{name:'PRIVATE_PERSON',monthly:100}];state.data.funds=[{balance:500,months:[]}];let row={version:0,payload:JSON.stringify(state)};const DB={prepare(sql){return {bind(...a){this.a=a;return this;},async first(){return {...row};},async run(){if(sql.startsWith('UPDATE')){if(this.a[1]!==row.version)return {meta:{changes:0}};row={version:row.version+1,payload:this.a[0]};return {meta:{changes:1}};}return {meta:{changes:0}};}};}};return {env:{DB,ADMIN_EMAIL:OWNER},worker:createWorker('<p>Dashboard</p>')};}
const req=(email,path='/api/data',method='GET',body)=>new Request('https://lab.example'+path,{method,headers:{...(email?{'oai-authenticated-user-id':'verified-id','oai-authenticated-user-email':email}:{}),...(method==='PUT'?{'Origin':'https://lab.example','Content-Type':'application/json','X-Lab-Request':'1'}:{})},...(body?{body:JSON.stringify(body)}:{})});
test('anonymous and unapproved users cannot read HTML or API',async()=>{const {worker,env}=fixture();assert.equal((await worker.fetch(req(null),env)).status,401);assert.equal((await worker.fetch(req('unknown@example.test','/'),env)).status,403);});
test('student API excludes financial data and faculty points',async()=>{const {worker,env}=fixture();const r=await worker.fetch(req('student@example.test'),env);assert.equal(r.status,200);const d=await r.json();assert.deepEqual(d.data.payroll,[]);assert.deepEqual(d.data.funds,[]);assert.ok(!JSON.stringify(d).includes('PRIVATE_PERSON'));assert.equal(d.data.papers[0].points,undefined);assert.deepEqual(d.students,[]);});
test('student cannot upload data or grant accounts',async()=>{const {worker,env}=fixture();for(const path of ['/api/data','/api/students'])assert.equal((await worker.fetch(req('student@example.test',path,'PUT',{version:0,data:fresh().data,students:[]}),env)).status,403);});
test('owner updates persist and stale saves are rejected',async()=>{const {worker,env}=fixture();const input={version:0,students:['new@example.test']};assert.equal((await worker.fetch(req(OWNER,'/api/students','PUT',input),env)).status,200);assert.equal((await worker.fetch(req(OWNER,'/api/students','PUT',input),env)).status,409);assert.equal((await worker.fetch(req('new@example.test'),env)).status,200);assert.equal((await worker.fetch(req('student@example.test'),env)).status,403);});
test('cross origin mutation blocked',async()=>{const {worker,env}=fixture(),r=req(OWNER,'/api/data','PUT',{version:0,data:fresh().data});r.headers.set('Origin','https://other.example');assert.equal((await worker.fetch(r,env)).status,403);});
test('direct conference and expense edits persist without replacing original months',async()=>{const {worker,env}=fixture();const original=await (await worker.fetch(req(OWNER),env)).json();const d=original.data;d.conferences.push({id:'direct',manual:true,year:2026,date:'2026-09-20',presenter:'Researcher',conference:'Conference',kind:'구두'});d.funds[0].months=[{month:'8월',spend:100,balance:500}];d.funds[0].entries=[{id:'expense',date:'2026-09-20',description:'Supplies',amount:120,note:''}];assert.equal((await worker.fetch(req(OWNER,'/api/data','PUT',{version:0,data:d}),env)).status,200);const saved=await (await worker.fetch(req(OWNER),env)).json();assert.deepEqual(saved.data,d);d.funds[0].entries[0].amount=150;assert.equal((await worker.fetch(req(OWNER,'/api/data','PUT',{version:1,data:d}),env)).status,200);const edited=await (await worker.fetch(req(OWNER),env)).json();assert.equal(edited.data.funds[0].entries[0].amount,150);assert.deepEqual(edited.data.funds[0].months,[{month:'8월',spend:100,balance:500}]);});
test('invalid direct entries are rejected without changing saved records',async()=>{for(const change of [d=>d.funds[0].entries[0].amount=-1,d=>d.funds[0].entries[0].amount=1.5,d=>d.funds[0].entries[0].date='2026-02-30',d=>d.funds[0].entries[0].description=' ',d=>d.conferences[0].year=2025]){const {worker,env}=fixture();const d=(await (await worker.fetch(req(OWNER),env)).json()).data;d.funds[0].entries=[{date:'2026-09-20',description:'Supplies',amount:120}];d.conferences=[{manual:true,year:2026,date:'2026-09-20',presenter:'Researcher',conference:'Meeting',kind:'구두'}];change(d);assert.equal((await worker.fetch(req(OWNER,'/api/data','PUT',{version:0,data:d}),env)).status,400);assert.equal((await (await worker.fetch(req(OWNER),env)).json()).version,0);}});
